import { useMemo, useState } from 'react'
import { mapLifeSavingRules } from '../data/lifeSavingRules'
import { mapPrecursors } from '../services/precursorMapper'
import { getPriority } from '../services/reviewPriority'
import EvidenceTags from './EvidenceTags'

function ReportTable({ reports = [] }) {
  const [prediction, setPrediction] = useState('ALL')
  const [confidence, setConfidence] = useState('ALL')
  const [priority, setPriority] = useState('ALL')
  const [descending, setDescending] = useState(true)
  const filtered = useMemo(() => reports.map((report, index) => ({ ...report, _index: index, priority: getPriority(report.prediction, report.probability) })).filter((report) => prediction === 'ALL' || report.prediction === prediction).filter((report) => confidence === 'ALL' || report.confidence === confidence).filter((report) => priority === 'ALL' || report.priority === priority).sort((a, b) => (descending ? b.probability - a.probability : a.probability - b.probability)), [reports, prediction, confidence, priority, descending])

  return <div className="table-panel"><div className="table-tools"><select value={prediction} onChange={(event) => setPrediction(event.target.value)} aria-label="Filter prediction"><option value="ALL">All predictions</option><option value="SIF_POTENTIAL">SIF potential</option><option value="NOT_APPARENT">Not apparent</option></select><select value={confidence} onChange={(event) => setConfidence(event.target.value)} aria-label="Filter confidence"><option value="ALL">All confidence</option><option value="HIGH">High</option><option value="MEDIUM">Medium</option><option value="LOW">Low</option></select><select value={priority} onChange={(event) => setPriority(event.target.value)} aria-label="Filter priority"><option value="ALL">All priorities</option><option value="HIGH">High priority</option><option value="MEDIUM">Medium priority</option><option value="LOW">Low priority</option></select><button type="button" onClick={() => setDescending((value) => !value)}>Probability {descending ? '↓' : '↑'}</button><span className="table-count">{filtered.length} of {reports.length} reports</span></div><div className="table-scroll"><table className="report-table"><thead><tr><th>OSHA ID</th><th>Prediction</th><th>Probability</th><th>Confidence</th><th>Precursor</th><th>Life-Saving Rule</th><th>Evidence</th><th>Review priority</th></tr></thead><tbody>{filtered.map((report) => { const evidenceText = (report.evidence || []).map((item) => item.term).join(' '); const precursors = mapPrecursors(evidenceText, report.evidence); const rules = mapLifeSavingRules(evidenceText); return <tr key={`${report.osha_id || 'row'}-${report._index}`}><td className="report-id">{report.osha_id || '—'}</td><td><span className={`pill ${report.prediction === 'SIF_POTENTIAL' ? 'sif' : 'not'}`}>{report.prediction === 'SIF_POTENTIAL' ? 'SIF potential' : 'Not apparent'}</span></td><td className="probability">{(report.probability * 100).toFixed(1)}%</td><td>{report.confidence}</td><td><div className="compact-cell">{precursors.slice(0, 2).map((item) => <span key={item.code}>{item.name}</span>)}</div></td><td><div className="compact-cell">{rules.slice(0, 2).map((rule) => <span key={rule.id}>{rule.name}</span>)}</div></td><td><div className="evidence-cell"><EvidenceTags evidence={report.evidence} /></div></td><td><span className={`priority-badge priority-${report.priority.toLowerCase()}`}>{report.priority}</span></td></tr> })}</tbody></table></div>{!filtered.length && <div className="empty-state">No reports match the current filters.</div>}</div>
}

export default ReportTable